version: '3'

services:
  php:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../www:/var/www/html

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_app
    volumes:
      - ../mysql_data:/var/lib/mysql
